# Generated by Django 5.0.6 on 2024-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudDetail',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('sclass', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('socialscience', models.IntegerField()),
            ],
        ),
    ]
